DATASET_FILEPATH = "data/input.json"

SUBSET_SIZE = None

CHUNK_LENGTH = 5
CHUNK_OVERLAP = 2

CHUNK_CLEANING_TOC_PERIOD_THRESHOLD = 0.3
CHUNK_CLEANING_LENGTH_MINIMUM = 30
CHUNK_CLEANING_LENGTH_MAXIMUM = 500

EMBEDDING_MODEL_NAME = "sentence-transformers/all-MiniLM-L6-v2"

TOP_N_SIMILAR_CHUNKS = 10
TOP_K_CONTRADICTIONS = 20
SENTENCE_SIMILARITY_THRESHOLD = 0.7
